#created on: 19.09.2012
package de.lehsten.casa.rules.location

import de.lehsten.casa.contextserver.types.entities.place.Stop;
import de.lehsten.casa.contextserver.types.entities.services.websites.Website;
import de.lehsten.casa.contextserver.types.entities.services.websites.LocationWebsite;

rule "InsertPublicTransportService"
@Importer("PublicTransport")
@ImporterRequestIntervall("Once")
@ImporterParameter0("Position location")
@ImporterParameter1("Double Radius")
	when
		s : Stop(stopNumber != null)
		not LocationWebsite(places contains s) 
	then
		System.out.println("Adding LocationWebsite for "+ s.getStopNumber());
		LocationWebsite lw = new LocationWebsite(s);
		lw.setSource("Rule: IPTS");
		lw.getProperties().put("stopNumber", Integer.toString(s.getStopNumber()));
		lw.setDescription("Public transport plan for "+ s.getTitle());
		lw.setTitle(s.getTitle() + " public transport plan");
		lw.setTargetURL(("http://reiseauskunft.bahn.de/bin/bhftafel.exe/dn?input="+s.getStopNumber()+"&boardType=dep&time=actual&productsDefault=111111111&start=yes"));
		insert(lw);
end

//DEMO
/*
rule "AddPublicTransportService"
@Importer("PublicTransport")
	when
		r : Request(userID != null)
		s : Stop(stopNumber != null)
		m : MobilePhone( owner == r.userID && nearbyPlaces contains c)
	then
		PublicTransportService pts = new PublicTransportService(s);
		pts.setSource("PublicTransportService for"+r.userID);
		pts.setTitle(s.getTitle() + " Haltestellenabfahrtsplan");
		pts.setTargetURL(("http://reiseauskunft.bahn.de/bin/bhftafel.exe/dn?input="+s.getStopNumber()+
						  "&boardType=dep&time=actual&productsDefault="+s.getProducts()+"&start=yes"));
		r.addResult(lw);
end
*/
rule "AddStopLocationToPublicTransportService"
	when
		s : Stop(stopNumber != null)
		lw1 : LocationWebsite(places contains s)
		lw2 : LocationWebsite(description == lw1.description && places not contains s);
	then
		System.out.println("Double found!");
		System.out.println("lw1:" + lw1.getProperties());
		System.out.println("lw2:" + lw2.getProperties());
		lw2.setPlaces(lw1.getPlaces());
		retract(lw1);
end

