#created on: 19.09.2012
package de.lehsten.casa.rules.location

import de.lehsten.casa.contextserver.types.entities.person.Person;
import de.lehsten.casa.contextserver.types.entities.place.Cafeteria;
import de.lehsten.casa.contextserver.types.entities.device.MobilePhone;

rule "LactoseFreeMenuNotification" 
	when
		c : Cafeteria(lactosefree_menu_available == true)
		m : MobilePhone(notifications not contains c.lactosefree_menu, nearbyPlaces contains c )
		p : Person( activeDevices contains m, properties["allergy"] == "lactose" )
	then
		System.out.println("Lactosefree Cafeteria found");
		m.addNotification(c.getLactosefree_menu()); 
end

