#created on: 27.09.2012
package de.lehsten.casa.rules.studip.services

#list any import classes here.

import de.lehsten.casa.contextserver.types.entities.person.identity.Identity;
import de.lehsten.casa.contextserver.types.entities.event.Course;
import de.lehsten.casa.contextserver.types.entities.event.Lecture;
import de.lehsten.casa.contextserver.types.entities.services.websites.EventWebsite;
import java.util.Date;

#declare any global variables here

function Date now() {
    return new Date();
}

function String hello(String name) {
    return "Hello "+name+"!";
}



rule "EventWebsiteForNextCourse"
	when
			i : Identity()
			l : Lecture (eval(beginDate.after(now())))
			not Lecture (beginDate before l.beginDate)
//			c : Course (members contains i, lectures contains l)
			not EventWebsite(event == l)
	then 
			System.out.println("Adding Website for Next Lecture");
			EventWebsite s = new EventWebsite(l);
			s.setTitle("Next Lecture: "+ l.getTitle());
			s.setProvider("StudIP");
			s.setTargetURL("http://localhost/studip20/public/seminar_main.php?cid="+l.getStudIP_ID());
			s.setSource("EventWebsiteForNextCourse");
			insert(s);
end

rule "EventWebsiteForEveryCourse"
	
	when
			c : Course ()
			not EventWebsite(event == c)
	then 
			System.out.println("Adding Website for Course");
			EventWebsite s = new EventWebsite(c);
			s.setTitle("Course: "+c.getTitle() );
			s.setProvider("StudIP");
			s.setTargetURL("http://localhost/studip20/public/details.php?sem_id="+c.getStudIP_ID());
			s.setSource("WebsiteForCourse");
			insert(s);
end



