#created on: 19.09.2012
package de.lehsten.casa.rules.location 
 
import de.lehsten.casa.contextserver.types.entities.device.MobilePhone;
import de.lehsten.casa.contextserver.types.position.MovementEvent;

rule "HandleLocationUpdates"
	when
		m : MobilePhone()
		p : MovementEvent( deviceID == m.deviceID) //from entry-point "StudIPEntryPoint"
	then
		System.out.println("LocationUpdate received.");
		modify(m){
			setLocation(p)
		}
		retract(p);
end

